#ifndef COMMON_HPP
#define COMMON_HPP

#include <string>

const std::string card_string[] = {
	"2C", "3C", "4C", "5C", "6C", "7C", "8C", "9C", "10C", "JC", "QC", "KC", "AC",
	"2D", "3D", "4D", "5D", "6D", "7D", "8D", "9D", "10D", "JD", "QD", "KD", "AD",
	"2S", "3S", "4S", "5S", "6S", "7S", "8S", "9S", "10S", "JS", "QS", "KS", "AS",
	"2H", "3H", "4H", "5H", "6H", "7H", "8H", "9H", "10H", "JH", "QH", "KH", "AH",
	"JOKER"};

typedef enum card_type
{
	TWOCLUBS,
	THREECLUBS,
	FOURCLUBS,
	FIVECLUBS,
	SIXCLUBS,
	SEVENCLUBS,
	EIGHTCLUBS,
	NINECLUBS,
	TENCLUBS,
	JACKCLUBS,
	QUEENCLUBS,
	KINGCLUBS,
	ACECLUBS,
	TWODIAMONDS,
	THREEDIAMONDS,
	FOURDIAMONDS,
	FIVEDIAMONDS,
	SIXDIAMONDS,
	SEVENDIAMONDS,
	EIGHTDIAMONDS,
	NINEDIAMONDS,
	TENDIAMONDS,
	JACKDIAMONDS,
	QUEENDIAMONDS,
	KINGDIAMONDS,
	ACEDIAMONDS,
	TWOSPADES,
	THREESPADES,
	FOURSPADES,
	FIVESPADES,
	SIXSPADES,
	SEVENSPADES,
	EIGHTSPADES,
	NINESPADES,
	TENSPADES,
	JACKSPADES,
	QUEENSPADES,
	KINGSPADES,
	ACESPADES,
	TWOHEARTS,
	THREEHEARTS,
	FOURHEARTS,
	FIVEHEARTS,
	SIXHEARTS,
	SEVENHEARTS,
	EIGHTHEARTS,
	NINEHEARTS,
	TENHEARTS,
	JACKHEARTS,
	QUEENHEARTS,
	KINGHEARTS,
	ACEHEARTS,
	JOKER
};

#endif // COMMON_HPP